### ISSUE TITLE
No directory found

### ISSUE THREAD

**Issue by 2hands10fingers** [luminousmen/youtube_download#3]
I haven't been able to get this to work. I receive <pre>Traceback (most recent call last):
  File "youtube.py", line 196, in <module>
    get_videos(args.url)
  File "youtube.py", line 140, in get_videos
    download(url, title)
  File "youtube.py", line 151, in download
    with open(filename, 'wb') as dst_file:
IOError: [Errno 2] No such file or directory: u'J74 V-Module Tutorial 5 (Making of "In the Open Air" // OpenGL stuff)'</pre>

**Comment by luminousmen** [comment]
@2hands10fingers fixed in last commit
